# @param image Object containing image details for the Kermoo container
image:
  # @param image.registry Docker registry where the image is stored
  registry: docker.io
  
  # @param image.repository Repository of the Kermoo image
  repository: evryn/kermoo
  
  # @param image.tag Tag of the Kermoo image to use
  tag: latest

# @param commonLabels Object to specify common labels for all created resources
commonLabels: {}

# @param commonAnnotations Object to specify common annotations for all created resources
commonAnnotations: {}

# @param debug Flag to enable or disable verbose logging (true/false)
debug: false

# @param configuration Configuration settings for Kermoo container
configuration: |
  process:
    delay: 1s

# @param ports Define container (.targetPort) and associated service (.port) ports
services:
  - port: 80
    targetPort: 80
  - port: 8080
    targetPort: 8080

# @param replicaCount Integer specifying the number of pod replicas to be deployed
replicaCount: 1  

# @param additionalContainerTemplate Object containing additional template for Kermoo such as resource limits
# additionalContainerTemplate:
#   resources:
#     limits:
#       cpu: 200m
#       memory: 128Mi
additionalContainerTemplate: {}