apiVersion: apps/v1
kind: Deployment
metadata:
  name: kermoo-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kermoo
    spec:
      containers:
      - name: kermoo
        image: evryn/kermoo
        command: ["start"]
        ports:
        - containerPort: 80
        volumeMounts:
        - name: config-volume
          mountPath: /home/kerm/.kermoo/config.yaml
          subPath: config.yaml
      volumes:
      - name: config-volume
        configMap:
          name: kermoo-config
