apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
  {{- with .Values.commonLabels }}
  labels: 
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ $.Release.Name }}
  template:
    metadata:
      labels:
        app: {{ $.Release.Name }}
        {{- with .Values.commonLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.commonAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      containers:
      - name: kermoo
        image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        {{- if .Values.debug }}
        command: ["start", "-v", "debug"]
        {{- else }}
        command: ["start"]
        {{- end }}
        {{- if .Values.services }}
        ports:
          {{- range .Values.services }}
          - containerPort: {{ .targetPort }}
          {{ end }}
        {{- end }}
        volumeMounts:
        - name: config-volume
          mountPath: ~/.kermoo/config.yaml
          subPath: config.yaml
        {{- if .Values.additionalContainerTemplate -}}
        {{ toYaml .Values.additionalContainerTemplate | nindent 8 }}
        {{- end }}
      volumes:
      - name: config-volume
        configMap:
          name: {{ .Release.Name }}-config
