apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
  {{- with .Values.commonLabels }}
  labels: 
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  selector:
    app: kermoo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
