{{- range .Values.services }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $.Release.Name }}-service-{{ .port }}
  labels:
    app: {{ $.Release.Name }}
    {{- with $.Values.commonLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with $.Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .port }}
      targetPort: {{ .targetPort }}
      protocol: TCP
  selector:
    app: {{ $.Release.Name }}
---
{{- end }}
