# @param image Object containing image details for the Kermoo container
image:
  # @param image.registry Docker registry where the image is stored
  registry: docker.io
  
  # @param image.repository Repository of the Kermoo image
  repository: evryn/kermoo
  
  # @param image.tag Tag of the Kermoo image to use
  tag: latest

# @param commonLabels Object to specify common labels for all created resources
commonLabels: {}

# @param commonAnnotations Object to specify common annotations for all created resources
commonAnnotations: {}

# @param debug Flag to enable or disable verbose logging (true/false)
debug: false

# @param configuration Configuration settings for Kermoo container
configuration: |
  process:
    delay: 1s

# @param replicaCount Integer specifying the number of pod replicas to be deployed
replicaCount: 1  

# @param resources Object containing CPU/Memory resource requests and limits for the Kermoo container
resources:
  # @param resources.limits CPU/Memory resource limits for the Kermoo container
  # Example:
  # limits:
  #    cpu: 250m
  #    memory: 256Mi
  limits: {}
  
  # @param resources.requests CPU/Memory resource requests for the Kermoo container
  # Example:
  # requests:
  #    cpu: 250m
  #    memory: 256Mi
  requests: {}
